# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_beautify.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_image_beautify(object):
    def setupUi(self, image_beautify):
        image_beautify.setObjectName("image_beautify")
        image_beautify.resize(400, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(image_beautify)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(image_beautify)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(image_beautify)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(101)
        self.horizontalSlider.setSingleStep(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(image_beautify)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalSlider_3 = QtWidgets.QSlider(image_beautify)
        self.horizontalSlider_3.setMinimum(1)
        self.horizontalSlider_3.setSingleStep(5)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout_3.addWidget(self.horizontalSlider_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)

        self.retranslateUi(image_beautify)
        QtCore.QMetaObject.connectSlotsByName(image_beautify)

    def retranslateUi(self, image_beautify):
        _translate = QtCore.QCoreApplication.translate
        image_beautify.setWindowTitle(_translate("image_beautify", "人像美颜"))
        self.label.setText(_translate("image_beautify", "美白磨皮"))
        self.label_3.setText(_translate("image_beautify", "大眼程度"))
